### ISSUE TITLE
Add a trailing comma

### ISSUE THREAD

**Issue by decryphe** [jkelleyrtp/tokio-alt-select#1]
Hello!

We use basically this exact macro in our big internal project. When doing projects on my own, I really miss autoformatted tokio selects (can't live without rustfmt!).

One detail I saw is that this macro doesn't accept a final trailing comma - which would be useful for reducing noise in the git commit history in certain cases. Do you mind if I add an optional trailing comma to the macro?

Also: Why isn't this published on crates.io?

Regards Hans

**Comment by jkelleyrtp** [comment]
Sure, feel free to add it, and then I'll publish it.
